
ifeq ($(CONFIG_ECL_SRC_NETWORK_TCP_CLIENT),y)
SRC_NETWORK_TCP_SRCS=client.c
SRC_NETWORK_TCP_HDRS=client.h
SRC_NETWORK_TCP_TEST=client-test.c
endif

ifeq ($(CONFIG_ECL_SRC_NETWORK_TCP_SERVER),y)
SRC_NETWORK_TCP_SRCS+=server.c
SRC_NETWORK_TCP_HDRS+=server.h
endif

TARGETS+=SRC_NETWORK_TCP
